import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatAutocompleteModule,
  MatButtonModule,
  //MatButtonToggleModule,
  MatCardModule,
  MatCheckboxModule,
  //MatChipsModule,
  //MatDatepickerModule,
  MatDialogModule,
  MatDividerModule,
  //MatExpansionModule,

  //MatGridListModule,
  MatIconModule,
  MatInputModule,
  //MatListModule,
  MatMenuModule,
  //MatNativeDateModule,
  //MatPaginatorModule,
  MatProgressBarModule,
  //MatProgressSpinnerModule,
  //MatRadioModule,
  //MatRippleModule,
  MatSelectModule,
  MatSidenavModule,
  MatSliderModule,
  MatSlideToggleModule,
  //MatSnackBarModule,
  //MatSortModule,
  //MatStepperModule,
  //MatTableModule,
  //MatTabsModule,
  MatToolbarModule,
  MatFormFieldModule,
  //MatTooltipModule,
  //MatBottomSheetModule,
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatAutocompleteModule,
    MatButtonModule,
    //MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    //MatChipsModule,
    //MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    //MatExpansionModule,
    MatFormFieldModule,
    //MatGridListModule,
    MatIconModule,
    MatInputModule,
    //MatListModule,
    MatMenuModule,
    //MatNativeDateModule,
    //MatPaginatorModule,
    MatProgressBarModule,
    //MatProgressSpinnerModule,
    //MatRadioModule,
    //MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    //MatSnackBarModule,
    //MatSortModule,
    //MatStepperModule,
    //MatTableModule,
    //MatTabsModule,
    MatToolbarModule,
    //MatTooltipModule,
    //MatBottomSheetModule,

  ],
  exports: [
    MatAutocompleteModule,
    MatButtonModule,
    //MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    //MatChipsModule,
    //MatDatepickerModule,
    MatDialogModule,
    MatDividerModule,
    //MatExpansionModule,
    MatFormFieldModule,
    //MatGridListModule,
    MatIconModule,
    MatInputModule,
    //MatListModule,
    MatMenuModule,
    //MatNativeDateModule,
    //MatPaginatorModule,
    MatProgressBarModule,
    //MatProgressSpinnerModule,
    //MatRadioModule,
    //MatRippleModule,
    MatSelectModule,
    MatSidenavModule,
    MatSliderModule,
    MatSlideToggleModule,
    //MatSnackBarModule,
    //MatSortModule,
    //MatStepperModule,
    //MatTableModule,
    //MatTabsModule,
    MatToolbarModule,
    //MatTooltipModule,
    //MatBottomSheetModule,
  ]
})
export class MaterialModule { }
